

# realiser le 16 juiin 2025, autheur: QIU Hao
# Server PACS pour les images medicales 
# origine de docker compose configuration: https://github.com/orthanc-server/orthanc-setup-samples/tree/master



services:
  orthanc:
    image: orthancteam/orthanc
    depends_on:
      - orthanc-index
    restart: unless-stopped
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - type: bind
        source: /mnt/orthanc-storage
        target: /var/lib/orthanc/db
        read_only: false
    environment:
      VERBOSE_STARTUP: "true"
      VERBOSE_ENABLED: "false"
      ORTHANC__POSTGRESQL: |
        {
          "Host": "orthanc-index",
          "EnableVerboseLogs": true
        }
      ORTHANC__POSTGRESQL__PASSWORD: "xxxxxx"
      ORTHANC__POSTGRESQL__USERNAME: "postgres"
      ORTHANC__POSTGRESQL__DATABASE: "postgres"
      ORTHANC__NAME: "RTH41"
      ORTHANC__REGISTERED_USERS: |
        {"xxx": "xxxxxx"}
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      ORTHANC__DICOM_WEB__SERIES_METADATA: "Full"
      ORTHANC__DICOM_WEB__STUDIES_METADATA: "Full"
      ORTHANC__DICOM_WEB__METADATA_WORKER_THREADS_COUNT: "4"
      ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT: "DD/MM/YYYY"
      ORTHANC__DICOM_SERVER_ENABLED: "true"
      ORTHANC__DICOM_PORT: 4242
      ORTHANC__DICOM_AET: "orthancRTH41"
      ORTHANC__DICOM_MODALITIES: |
        {
          "cnc": {
            "AET": "cnc",
            "Host": "192.168.1.206",
            "Port": 4242,
            "AllowEcho": true,
            "AllowFind": true,
            "AllowMove": true,
            "AllowStore": true
          },
          "slice3D": {
            "AET": "CTKSTORE",
            "Host": "192.168.1.224",
            "Port": 11112,
            "AllowEcho": true,
            "AllowFind": true,
            "AllowMove": true,
            "AllowStore": true
          },
          "HAO02": {
            "AET": "ORTHANCHAO",
            "Host": "192.168.1.190",
            "Port": 4242,
            "AllowEcho": true,
            "AllowFind": true,
            "AllowMove": true,
            "AllowStore": true
          },
          "RTH41": {
            "AET": "orthancRTH41",
            "Host": "192.168.1.72",
            "Port": 4242,
            "AllowEcho": true,
            "AllowFind": true,
            "AllowMove": true,
            "AllowStore": true
          }
        }

  orthanc-index:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: /opt/orthanc-postgres-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "xxxxxx"
      PGDATA: /var/lib/postgresql/data/pgdata  # 避免权限问题
